# Generated by Django 3.0.8 on 2020-08-03 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crownspost',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='crownspost',
            name='Socials',
        ),
        migrations.AlterField(
            model_name='crownspost',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Crowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crownspost',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish to Home'), (2, 'Publish to Male wears'), (3, 'Publish to Female wears'), (4, 'Publish to T-Shirts'), (5, 'Publish to Joggers'), (6, 'Publish to Trousers'), (7, 'Publish to Gowns'), (8, 'Publish to Hoods'), (9, 'Publish to Vintages'), (10, 'Publish to foot wears')], default=0),
        ),
    ]
